env:
    TERM: xterm-256color

window:
    padding:
        x: 20
        y: 20

font:
    normal:
        family: DejaVu Sans Mono
        style: Book

    bold:
        family: DejaVu Sans Mono
        style: Bold

    italic:
        family: monospace
        style: italic

    size: 12


schemes:
    default: &default
        primary:
            background: '#101010'
            foreground: '#c5c8c6'

        cursor:
            cursor: '#c5c8c6'

        normal:
            black: '#1d1f21'
            red: '#cc6666'
            green: '#b5bd68'
            yellow: '#f0c674'
            blue: '#81a2be'
            magenta: '#b294bb'
            cyan: '#8abeb7'
            white: '#c5c8c6'

        bright:
            black: '#969896'
            red: '#cc6666'
            green: '#b5bd68'
            yellow: '#f0c674'
            blue: '#81a2be'
            magenta: '#b294bb'
            cyan: '#8abeb7'
            white: '#ffffff'

colors: *default
