#!/bin/bash

# Global Vars
##################################################
ACTIVE="$(pactl list sinks | grep -oP 'Active Port: analog-output-\K(headphones|lineout)')"
SINKNUM="$(pactl list short sinks | grep 'analog-stereo' | grep 'pci' | grep -oP '(^.)')"


# Execute
##################################################

# Mute the master so headphones don't accidentally get
#   100% volume sent through them.
amixer -q sset Master mute

# Switch
case $ACTIVE in
    "lineout")
        pactl set-sink-port "$SINKNUM" analog-output-headphones
        amixer -q sset Master 30% unmute;;
    "headphones")
        pactl set-sink-port "$SINKNUM" analog-output-lineout
        amixer -q sset Master 100% unmute;;
esac
